
/**
 * Program calculates end of day work log hours (total time worked).
 *
 * @author Nathan Thomas
 * @version 1.0
 */
public class LogCalculatorGUI extends javax.swing.JFrame {

   /**
    * Creates new form LogCalculatorGUI
    */
   public LogCalculatorGUI() {
      initComponents();
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jSpinner5 = new javax.swing.JSpinner();
      jSpinner1 = new javax.swing.JSpinner();
      jSpinner2 = new javax.swing.JSpinner();
      jSpinner3 = new javax.swing.JSpinner();
      jSpinner4 = new javax.swing.JSpinner();
      jFormattedTextField1 = new javax.swing.JFormattedTextField();
      clockIn1 = new java.awt.Label();
      clockOut1 = new java.awt.Label();
      lunch = new java.awt.Label();
      clockIn2 = new java.awt.Label();
      clockOut2 = new java.awt.Label();
      hour1 = new javax.swing.JTextField();
      hour2 = new javax.swing.JTextField();
      hour3 = new javax.swing.JTextField();
      hour4 = new javax.swing.JTextField();
      jButton1 = new javax.swing.JButton();
      logTime = new java.awt.Label();
      minute3 = new javax.swing.JTextField();
      minute1 = new javax.swing.JTextField();
      minute4 = new javax.swing.JTextField();
      minute2 = new javax.swing.JTextField();
      label1 = new java.awt.Label();
      label2 = new java.awt.Label();

      jFormattedTextField1.setText("jFormattedTextField1");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      clockIn1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      clockIn1.setName("Clock In"); // NOI18N
      clockIn1.setText("Clock In:");

      clockOut1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      clockOut1.setText("Clock Out:");

      lunch.setFont(new java.awt.Font("Dialog", 3, 24)); // NOI18N
      lunch.setText("LUNCH");

      clockIn2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      clockIn2.setText("Clock In:");

      clockOut2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      clockOut2.setText("Clock Out:");

      hour1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
      hour1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            hour1ActionPerformed(evt);
         }
      });

      hour2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
      hour2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            hour2ActionPerformed(evt);
         }
      });

      hour3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

      hour4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

      jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
      jButton1.setText("Calculate");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      logTime.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
      logTime.setText("Log Time: ");

      minute3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

      minute1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

      minute4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

      minute2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

      label1.setText("Hour");

      label2.setText("Minutes");

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(clockOut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(clockIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(clockIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(clockOut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
               .addComponent(hour3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
               .addComponent(hour2, javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(hour1, javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(hour4))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(minute3, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(minute1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(minute4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(minute2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(298, 298, 298))
         .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(layout.createSequentialGroup()
                  .addGap(108, 108, 108)
                  .addComponent(lunch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(52, 52, 52)
                  .addComponent(jButton1)
                  .addGap(22, 22, 22)
                  .addComponent(logTime, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createSequentialGroup()
                  .addGap(189, 189, 189)
                  .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addGap(29, 29, 29)
                  .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(75, Short.MAX_VALUE))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addGroup(layout.createSequentialGroup()
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(clockIn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hour1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minute1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(clockOut1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hour2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(minute2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(lunch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addComponent(clockIn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(hour3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(minute3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
               .addComponent(clockOut2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(hour4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(minute4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(33, 33, 33)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jButton1)
               .addComponent(logTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(31, Short.MAX_VALUE))
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void hour1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour1ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_hour1ActionPerformed

   private void hour2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hour2ActionPerformed
      // TODO add your handling code here:
   }//GEN-LAST:event_hour2ActionPerformed

   private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      int firstHour = Integer.parseInt(hour1.getText());
      int secondHour = Integer.parseInt(hour2.getText());
      int thirdHour = Integer.parseInt(hour3.getText());
      int fourthHour = Integer.parseInt(hour4.getText());
      int firstMinute = Integer.parseInt(minute1.getText());
      int secondMinute = Integer.parseInt(minute2.getText());
      int thirdMinute = Integer.parseInt(minute3.getText());
      int fourthMinute = Integer.parseInt(minute4.getText());
      int totalHours;
      int morningMinutes;
      int afternoonMinutes;
      int totalMinutes;

      if (secondHour < firstHour) {
         secondHour += 12;
      }
      if (fourthHour < thirdHour) {
         fourthHour += 12;
      }

      totalHours = (secondHour - firstHour) + (fourthHour - thirdHour);

      if (firstMinute == 00) {
         morningMinutes = secondMinute;
      } else {
         morningMinutes = (60 - firstMinute) + secondMinute;
         totalHours -= 1;
      }

      if (thirdMinute == 00) {
         afternoonMinutes = fourthMinute;
      } else {
         afternoonMinutes = (60 - thirdMinute) + fourthMinute;
         totalHours -= 1;
      }

      totalMinutes = morningMinutes + afternoonMinutes;

      while (totalMinutes >= 60) {
         totalMinutes -= 60;
         totalHours += 1;
      }

      logTime.setText(totalHours + " hours, " + totalMinutes + " minutes");

   }//GEN-LAST:event_jButton1ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(LogCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(LogCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(LogCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(LogCalculatorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new LogCalculatorGUI().setVisible(true);
         }
      });
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private java.awt.Label clockIn1;
   private java.awt.Label clockIn2;
   private java.awt.Label clockOut1;
   private java.awt.Label clockOut2;
   private javax.swing.JTextField hour1;
   private javax.swing.JTextField hour2;
   private javax.swing.JTextField hour3;
   private javax.swing.JTextField hour4;
   private javax.swing.JButton jButton1;
   private javax.swing.JFormattedTextField jFormattedTextField1;
   private javax.swing.JSpinner jSpinner1;
   private javax.swing.JSpinner jSpinner2;
   private javax.swing.JSpinner jSpinner3;
   private javax.swing.JSpinner jSpinner4;
   private javax.swing.JSpinner jSpinner5;
   private java.awt.Label label1;
   private java.awt.Label label2;
   private java.awt.Label logTime;
   private java.awt.Label lunch;
   private javax.swing.JTextField minute1;
   private javax.swing.JTextField minute2;
   private javax.swing.JTextField minute3;
   private javax.swing.JTextField minute4;
   // End of variables declaration//GEN-END:variables
}
